### ISSUE TITLE
createBrowserClient is incorrectly marked as deprecated when no options object is passed in 0.4.0-rc.3

### ISSUE THREAD

**Issue by harrisrobin** [supabase/ssr#15]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using `createBrowserClient`, typescript shows me a deprecation warning due to it not having the `getAll` and `setAll` methods as discussed in https://github.com/orgs/supabase/discussions/27037, however this is only required for server clients since the browser client works with the document.cookie API by default. 

note that adding an empty object as the third argument also seems to remove this warning.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

In a typescript file, simply call `createBrowserClient` without the third options argument:
```ts
  createBrowserClient<MyDatabase>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)
  ```

## Expected behavior
It should not show me a deprecated warning if i don't pass it an options object.

## Screenshots

<img width="930" alt="image" src="https://github.com/supabase/ssr/assets/3880008/7ae2c7ab-87b2-4d24-b289-3d0163c1f4a5">

**Comment by hf** [comment]
Fixed with #17
