### ISSUE TITLE
Inconsistent `storageKey` usage.

### ISSUE THREAD

**Issue by activenode** [supabase/ssr#19]
# Chore

## Describe the chore

Currently, the only way to set the `storageKey` is using `options.cookieOptions.name`. However, for people working with both libraries, this can come confusing, although targeting the same thing in the end.

So I'm asking to have `options.auth.storageKey` support in this library officially.

## Additional context

Current version: https://github.com/supabase/ssr/blob/main/src/createBrowserClient.ts#L147-L148

**Comment by j4w8n** [comment]
@activenode can you share some code that's failing to give your expected results, or provide a reproduction? I'm not having this issue with ssr@0.5.1.

**Comment by j4w8n** [comment]
Now that I'm looking deeper, this may have been resolved in v0.4.0

**Comment by J0** [comment]
Closing as per discussion in #61, can re-open if issue persists
