### ISSUE TITLE
sveltekit doc not updated 0.4.0

### ISSUE THREAD

**Issue by zhihengGet** [supabase/ssr#23]
https://supabase.com/docs/guides/auth/server-side/sveltekit

here the createServerClient still uses get,set not same as nextjs

```
 createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
    cookies: {
      get: (key) => event.cookies.get(key),
      /**
       * SvelteKit's cookies API requires `path` to be explicitly set in
       * the cookie options. Setting `path` to `/` replicates previous/
       * standard behavior.
       */
      set: (key, value, options) => {
        event.cookies.set(key, value, { ...options, path: '/' })
      },
      remove: (key, options) => {
        event.cookies.delete(key, { ...options, path: '/' })
      },
    },
  })
```

**Comment by j4w8n** [comment]
This is being addressed by https://github.com/supabase/supabase/pull/27641

**Comment by j4w8n** [comment]
Looks like the PR was merged. Can you verify the docs and close this issue?

**Comment by vcheeze** [comment]
@zhihengGet @j4w8n I followed the updated docs to update from v0.3.0 to v0.4.0, but it seems the session is always `null`. Are the updated docs for SvelteKit up to date and tested to work? I am currently investigating my issue and will update here as well if I find anything.
