### ISSUE TITLE
Missing hooks for `useSupabaseClient`, `useUser`, `useSession`

### ISSUE THREAD

**Issue by bombillazo** [supabase/ssr#30]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Moved from [#744](https://github.com/supabase/auth-helpers/issues/744)

The documentation recommends that we migrate away from the `auth-helpers` lib in favor of the `ssr` library:

<img width="917" alt="image" src="https://github.com/supabase/auth-helpers/assets/44002321/0f3cac21-625d-4a18-a58c-57119b28377a">

The issue is that the `@supabase/ssr` library is missing essential React hooks for fetching the client and user auth data that we get from `@supabase/auth-helpers-react`. The docs should be updated if these hooks are not intended to be part of the SSR package. Importing both packages may create redundancy and multiple instance issues as specified [here](https://github.com/supabase/auth-helpers/issues/739).

## To Reproduce

N/A

## Expected behavior

To replace `auth-helpers` with `ssr`, the hooks that were available before would also be available in the `ssr` package.

## System information

- Version of supabase-js: 2.44.2

**Comment by hf** [comment]
This is not planned.

**Comment by bombillazo** [comment]
If that is the case, I recommend clearing up the documentation, it is very misleading
https://supabase.com/docs/guides/auth/auth-helpers

**Comment by C4T4** [comment]
Supabase Auth is an absolut mess right now. "We strongly recommend using the new @supabase/ssr package" - please don't.

**Comment by bombillazo** [comment]
@hf so... we _do_ need `@supabase/auth-helpers-react`?
