### ISSUE TITLE
Version `0.4.1` is not published to npm under the `latest` tag

### ISSUE THREAD

**Issue by aloisklink** [supabase/ssr#39]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The `0.4.1` release of `@supabase/ssr` is not published to npm under the `latest` tag. This means that most users won't automatically update to it, so they'd be affected by bugs like:
- https://github.com/supabase/ssr/pull/27
- https://github.com/supabase/ssr/pull/32

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://www.npmjs.com/package/@supabase/ssr
2. See that the latest version is `0.4.0`, not `0.4.1` (since that's only under the `patched` tag)

This means that running `npm install @supabase/ssr` will install `0.4.0` and not `0.4.1`. And any commands like `npm update` or @renovatebot or @dependabot will not show the updated version.

## Expected behavior

The `latest` tag on NPM should be `0.4.1`

## Screenshots

![image](https://github.com/user-attachments/assets/9f5e37ee-1d7f-486e-a619-ee3af7954eff)

![image](https://github.com/user-attachments/assets/0cf94ace-ebb0-42ca-bd0d-4e74701f2dda)

## System information

- OS: Linux
- Browser (if applies) N/A
- Package manager, tested on both:
  - pnpm 9.5.0
  - npm 10.5.2
- Version of supabase-js: 2.44.3
- Version of Node.js: v20.13.1

## Additional context

You should be able to use `npm dist-tag` to update the `latest` tag to `0.4.1`, see https://docs.npmjs.com/cli/v10/commands/npm-dist-tag for instructions.

**Comment by silentworks** [comment]
Version `0.5.0` was published as `latest` which contain the bug fixes mentioned above too.

**Comment by aloisklink** [comment]
> Version `0.5.0` was published as `latest` which contain the bug fixes mentioned above too.

That seems to have fixed it, at least for @renovatebot!

Hopefully in a week or two, we should see at https://www.npmjs.com/package/@supabase/ssr?activeTab=versions that everybody on `0.4.0` migrates to either `0.4.1` (e.g. if they had `^0.4.0` in their `package.json`) or `0.5.0`!

Fixed by https://github.com/supabase/ssr/pull/28
