### ISSUE TITLE
Using @supabase/ssr in Expo with API Routes

### ISSUE THREAD

**Issue by trevorpfiz** [supabase/ssr#42]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-expo-react-native
https://docs.expo.dev/router/reference/api-routes/

## Describe the problem

With the introduction of Expo API Routes, should we be using the `@supabase/ssr` package to handle auth in Expo?

## Describe the improvement

I would like some clarity on the preferred pattern for auth in a project using Expo API Routes.

## Aditional Context

Curious how to migrate from `auth-helpers` in https://github.com/supabase-community/create-t3-turbo to `@supabase/ssr`. Is this possible? Thanks!

**Comment by J0** [comment]
Hey @trevorpfiz 

Thanks for the query, migration should be similar to [the serve side framework guides](https://supabase.com/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers?queryGroups=framework&framework=nextjs)

Not familiar with ExpoAPI but it sounds like it's meant to act as and/or operate on a server. If it offers the equivalent of cookies or similar storage mechanism you should be able to use it.

As a final add on, SSR is an opinionated configuration of supabase-js so if using vanilla `supabase-js` suits your needs do feel free to use that as well. It should work fine.

Hope this helps and let us know if there are questions or concerns

**Comment by J0** [comment]
Hey,

Closing for now but feel free to re-openor let us know if there are any further questions or concerns
