### ISSUE TITLE
Causing Unnecessary Edge Function Invocation

### ISSUE THREAD

**Issue by prestonbourne** [supabase/ssr#48]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. ( i guess i can't quite click this because it seems to be an interoperability problem as opposed to one with the lib itself, still figured its worth opening the issue)
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## What I am trying to achieve

I wanted to migrate from [the original `supabase-js` package](https://github.com/supabase/supabase-js) to this `supabase-ssr` package. Currently, the functionality i have works just fine, until i swap in the ssr client, so my best guess it something with my misuse of cookies.

I have a blog, I am tracking views for each blog post in supabase, every time someone visits the route, I want the amount of views to be incremented. Using `@supabase/ssr` this works perfect locally, (dev mode and production builds) but once I actually deploy, the weird behavior begins. When I am in a preview or full production environment, the function that invokes the increment is being called twice due to edge functions.

## Screenshots

See here the first request from my browser client running on my macbook, expected and desired
<img width="674" alt="Vercel logs showing an RPC call to supabase where to request user agent is a macbook" src="https://github.com/user-attachments/assets/4ca99d08-0b00-4e55-9ba4-160fd61abee6">

Then here, the edge function request, unexpected and undesired
<img width="679" alt="Vercel logs showing an RPC call to supabase where to request user agent is a edge function" src="https://github.com/user-attachments/assets/8718c118-dc1f-4bd5-92ef-3d8a1347776f">

i don't have any server actions, "use server" directives, middleware, api routes or anything like that, I was calling this straight from the server component in typical ssr fashion.

### The Supabase Client

```ts
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { Database } from "./types";

const getEnv = (key: string): string => {
  if (!process.env[key]) {
    throw new Error(`Missing env.${key}`);
  }
  return process.env[key]!;
};

const supabaseUrl = getEnv("SUPABASE_URL");
const supabaseKey = getEnv("SUPABASE_KEY");

export const supabase = (cookies: CookieOptions) => {
  const cookieStore = cookies();

  return createServerClient<Database>(supabaseUrl, supabaseKey, {
    cookies: {
      get(name: string) {
        return cookieStore.get(name)?.value;
      },
    },
  });
};
export type Supabase = typeof supabase;
export type { CookieOptions };
```

### The Server Component

```tsx
/* 
wrapped in Suspense to handle loading ui, 
*/
export async function ViewCount({
  slug,
  shouldIncrement = false,
}: ViewCountProps) {
  console.log("`ViewCount` render", { props: { slug, shouldIncrement } });
  let views = 0;
  const inProd = process.env.NODE_ENV === "production";
  if (shouldIncrement && inProd) {
    views = await incrementViewsBySlug(slug, cookies);
    console.log("`ViewCount.incrementViews`", {
      views,
      slug,
    });
    return <BlogStat text={views} Icon={EyeOpenIcon} />;
  }
  const { data, error } = await fetchPostBySlug(slug, cookies);
  if (error || !data || !data.views) {
    return null;
  }
  views = data.views;
  return <BlogStat text={views} Icon={EyeOpenIcon} />;
}
```

### The Method Implementations
```ts
export const incrementViewsBySlug = async (
  slug: string,
  supabase: SupabaseClient
): Promise<Result<number>> => {
  console.log("`incrementViewsBySlug` called");
  const { error, data } = await supabase.rpc("increment_note_views", {
    note_slug: slug,
  });

  if (error) {
    console.error("Error incrementing note views", error);
    return { data: null, error: makeSupabaseError(error) };
  }
  return { data, error: null };
};

export const fetchPostBySlug = async (
  slug: string,
  supabase: SupabaseClient
): Promise<Result<Note>> => {
  console.log("`fetchRemoteNoteBySlug` called");
  const { data, error } = await supabase
    .from("notes")
    .select("*")
    .eq("slug", slug)
    .single();

  if (error) {
    console.error("Error fetching note", error);
    return { data: null, error: makeSupabaseError(error) };
  }

  const validData = isValidNoteRow(data);
  if (!validData) {
    return {
      data: null,
      error: new Error("Invalid note returned from database"),
    };
  }
  const mappedData = extractNoteFromRow(data);

  return { data: mappedData, error: null };
};
```

## To Reproduce

Unfortunately it seems like to reproduce you'll need a nextjs app deployed to vercel.
If a minimum viable repro is really necessary, i can _attempt_ to workshop a way to give someone access to a specific deployed project, but I think vercel makes you pay for having 2 people on a single hobby project

1. Spin up a nextjs template
2. Copy the ssr client
3. Invoke an RPC from the client and log on each function call
4. View Vercel logs

**Comment by j4w8n** [comment]
What `supabase` and `supabase/ssr` versions are you running?

**Comment by prestonbourne** [comment]
> What `supabase-js` and `supabase/ssr` versions are you running?

Hello! Latest versions on both

```json
 "@supabase/supabase-js": "^2.43.4"
 "@supabase/ssr": "^0.4.1"
```

**Comment by j4w8n** [comment]
Ok, good.

I'm not sure how much of an impact this is going to have, but can you try using the newer `getAll()` and `setAll()` functions?

I don't know Next, but based on your existing code, I'm guessing it's going to be similar to step 3 here, for the "utils/supabase/server.ts" code: https://supabase.com/docs/guides/auth/server-side/nextjs

**Comment by prestonbourne** [comment]
@j4w8n 

That worked, turn out I just needed to take a better look at the docs, thanks!

I see that [the method is deprecated now](https://github.com/supabase/ssr/blob/9cd6813b3ce3d00b8f67f9aa4949868b0908a591/src/createServerClient.ts#L24) ?

**Comment by j4w8n** [comment]
> @j4w8n 
> 
> That worked, turns out I just needed to take a better look at the docs, thanks!
> 
> I see that [the method is deprecated now](https://github.com/supabase/ssr/blob/9cd6813b3ce3d00b8f67f9aa4949868b0908a591/src/createServerClient.ts#L24) ?

Yeah, the old set, get, remove were deprecated as of v4.

**Comment by prestonbourne** [comment]
> Yeah, the old set, get, remove were deprecated as of v4.

good call, should prevent anyone from repeating my mistake. anyway, as far as i'm concerned this is resolved. i'll leave it up to your discretion to close the issue 👍

thanks again for the help

**Comment by j4w8n** [comment]
@prestonbourne I don't have the power to close issues, so would you mind doing that?
