### ISSUE TITLE
The `verifyOtp` method with the type "recovery" does not correctly log in the user

### ISSUE THREAD

**Issue by dvenomb98** [supabase/ssr#51]
-  I confirm this is a bug with Supabase, not with my own application. 
-  I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I attempted to implement a password recovery flow in my current application, which is built with Next.js 14 and @supabase-ssr 0.4. The implementation follows the documentation closely.

When a user receives a password recovery link via email and is redirected to /auth/confirm?token_hash&type&next, the verifyOtp method successfully returns the current user from the data. However, these changes are only applied locally within the /auth/confirm route and do not propagate to the middleware or other parts of the application.

Code:

app/auth/confirm/route.ts

```typescript
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type") as EmailOtpType | null;
  const next = searchParams.get("next") ?? "/";

  if (token_hash && type) {
    const supabase = createClient();

    const { data, error } = await supabase.auth.verifyOtp({
      type,
      token_hash,
    });
 // data returns user sucessfully here

// Current fix: I had to manually a set a session to fix behavior.
    if (type === "recovery" && !!data.session) {
      await supabase.auth.setSession({
        access_token: data.session.access_token,
        refresh_token: data.session.refresh_token,
      });
    }

    if (!error) {
      // redirect user to specified redirect URL or root of app
    
      redirect(next);
    }
  }
  // redirect the user to an error page with some instructions
  redirect("/error");
}
```

middleware.ts

```typescript
// Configuration was implemented as per the official documentation without any changes.

const {
  data: { user },
} = await supabase.auth.getUser();

// At this point, data.user is undefined, causing subsequent logic to fail.

// Additional logic was also implemented as per the documentation without any modifications.
```

## Expected Behavior

The `verifyOtp` method should successfully log in the user and correctly set the session across all parts of the application, ensuring that the user is authenticated and recognized not just locally within the `/auth/confirm` route, but throughout the entire application.

## System information

- OS: macOs
- Browser: any
- Version of supabase-js: 2.44.4,
- Version of Node.js: 20.16.0

## Additional context

I would like to hear out some opinions on current fix with setSession inside /auth/confirm. Is it safe to implement?

**Comment by j4w8n** [comment]
There's a bug for this in ssr v0.4.0. If you upgrade to the latest version, you should be fixed.

**Comment by dvenomb98** [comment]
Updated to 0.5 and seems fixed! Thank you
