### ISSUE TITLE
Unable to Create Client with Service Role Key

### ISSUE THREAD

**Issue by mariojfduarte** [supabase/ssr#59]
### Description

After recent changes in the createServerClient.ts file, it seems that creating a client with a service role key is no longer possible. Previously, my code allowed this by setting the admin flag to true so that Service Role Key was used, but now, even with the correct environment variables set, the client does not retain service role permissions as expected. I suspect this might be related to the changes in session persistence.

### Code References

**Before:**

```
export const createClient = (options?: CreateClientOptions) => {
  const { admin = true, ...rest } = options ?? {};

  const cookieStore = cookies();

  const key = admin
    ? process.env.NEXT_SUPABASE_SERVICE_ROLE_KEY!
    : process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

  const auth = admin
    ? {
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      }
    : {};

  return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, key, {
    ...rest,
    cookies: {
      get(name: string) {
        return cookieStore.get(name)?.value;
      },
      set(name: string, value: string, options: CookieOptions) {
        try {
          cookieStore.set({ name, value, ...options });
        } catch (error) {}
      },
      remove(name: string, options: CookieOptions) {
        try {
          cookieStore.set({ name, value: "", ...options });
        } catch (error) {}
      },
    },
    auth,
    global: {
      headers: {
        "user-agent": headers().get("user-agent") as string,
      },
    },
  });
};
```

**After:**

```
return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, key, {
  ...rest,
  cookies: {
    getAll() {
      return cookieStore.getAll();
    },
    setAll(cookiesToSet) {
      try {
        for (const { name, value, options } of cookiesToSet) {
          cookieStore.set(name, value, options);
        }
      } catch (error) {}
    },
  },
  auth,
  global: {
    headers: {
      "user-agent": headers().get("user-agent") as string,
    },
  },
});
```

### Problem
The recent changes seem to have removed the ability to create a client with a service role key. Even when the admin flag is set to true, the client does not behave as expected with service role permissions. This could be related to the session persistence or other changes in the client creation process.

### Suspected Cause
The issue may stem from the configuration of persistSession, autoRefreshToken, or other related authentication settings. These may be preventing the client from properly maintaining service role permissions.

### Suggested Solution
Investigate the interaction between the auth options and the ability to use service role keys. It may be necessary to adjust how session persistence or other authentication features are handled when using service role permissions.

### Additional Context
This issue was observed in the createServerClient.ts file after the following commit: 

[549fe62813fb9c7277f7eda9e46ee0420f8e0b5f](https://github.com/supabase/ssr/blob/549fe62813fb9c7277f7eda9e46ee0420f8e0b5f/src/createServerClient.ts#L177).

**Comment by j4w8n** [comment]
You should be using `createClient()` from @supabase/supabase-js to create a service role client, not ssr versions.

**Comment by mariojfduarte** [comment]
> You should be using `createClient()` from @supabase/supabase-js to create a service role client, not ssr versions.

why?

**Comment by mariojfduarte** [comment]
`return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, key, {
    // cookies: {
    //   getAll() {
    //     return cookieStore.getAll();
    //   },
    //   setAll(cookiesToSet) {
    //     try {
    //       for (const { name, value, options } of cookiesToSet) {
    //         cookieStore.set(name, value, options);
    //       }
    //     } catch (error) {}
    //   },
    // },
    auth,
  });`

if I comment it out, my query result alaways return null

**Comment by j4w8n** [comment]
A service role client shouldn't need to access cookies in order to work. What are you trying to accomplish?

**Comment by mariojfduarte** [comment]
I think this relates: https://github.com/orgs/supabase/discussions/27377#discussioncomment-10428125

**Comment by j4w8n** [comment]
Just to be clear, is your issue resolved?

**Comment by mariojfduarte** [comment]
No, I need to merge the pull request (currenlty using a fork). 

I can't bypass the auth options.

![image](https://github.com/user-attachments/assets/7fd4f541-74e9-4f5c-9700-5f2d23b7c1f9)

Why is it implemented this way?

```
auth: {
        ...(options?.cookieOptions?.name
          ? { storageKey: options.cookieOptions.name }
          : null),
        ...options?.auth,
        flowType: "pkce",
        autoRefreshToken: false,
        detectSessionInUrl: false,
        persistSession: true,
        storage,
      },
```

**This change solves my problem:**

```
auth: {
        ...(options?.cookieOptions?.name
          ? { storageKey: options.cookieOptions.name }
          : null),
        
        flowType: "pkce",
        autoRefreshToken: false,
        detectSessionInUrl: false,
        persistSession: true,
...options?.auth,
        storage,
      },
```

**Comment by j4w8n** [comment]
I guess I still don't understand why you can't use createClient from @supabase/supabase-js for this.

**Comment by mariojfduarte** [comment]
Correct, I'm using two clients.

Still, when using superbase-js native service role client is doesn't work. 

The only way to make it work is to pass the persistSession flag to false.

**Comment by j4w8n** [comment]
Can you show the code you're using to create the service role client?

**Comment by mariojfduarte** [comment]
it worked, thanks

**Comment by jerryshell** [comment]
> To be a bit more clear: you should be using both clients. The ssr server client to get the user data (presumably their id), then the native service role client to do the query thst bypasses RLS.

I ended up here because of a similar issue.
Compared to RLS, I prefer to implement the security model in Server Action, so I have been trying to pass `SUPABASE_SERVICE_ROLE_KEY` to the ssr version of `createServerClient`, but I kept encountering the error `new row violates row-level security policy`.
Finally, I solved my problem by following @j4w8n's suggestion: “using both clients”.
