### ISSUE TITLE
using custom_access_token_hook works in 0.3.0 but not in any newer packages

### ISSUE THREAD

**Issue by oldbettie** [supabase/ssr#66]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When upgrading from `v0.3.0` to any newer version of the ssr package it causes out custom jwt claims function to not work correctly. 

I can confirm, the only thing that was changed was this package.  We followed this to modify out JWT's
https://supabase.com/docs/guides/auth/auth-hooks/custom-access-token-hook?queryGroups=language&language=sql

It works fine with `v0.3.0` but when we use a later package the session cookie that is saved looks something like this
`_base64encoded<what_looks_like_the_jwt_access_key>` its not even an object its just literaly that as a string. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Createa project and activate the custom JWT hook and implementation
2. Create an account and try to login with SSR package `v0.3.0`
3. Change to package > 0.3.0 and repear
4. See cookie saved is not a real cookie

## Expected behavior

Should save the session cookie correctly

## System information

- OS: [macOS]
- Browser chrome
    "@supabase/ssr": "^0.4.0" || 0.5.1
    "@supabase/supabase-js": "^2.45.4"

**Comment by j4w8n** [comment]
So are you having an issue with the hook itself, or when trying to parse the session cookie?

**Comment by oldbettie** [comment]
I think the biggest issue is not that its an issue with the package but instead an issue with how you guys relay information about switching from v0.3 to v0.5. After loads of research I figured out that you have changed the cookie completely. We have many micro services including ones that are not integrated with supabase at all that just require the `access_token` and `refresh_token` from the cookie upgrading our core packages that mints JWT's to version 0..5 will require me to change every microservice we have to use the new cookie with the decoder. This should really be documented in detail somewhere

**Comment by j4w8n** [comment]
As you've probably noticed, they break the value into multiple cookies if having one is going to be too big. Are you running into issues with this?

**Comment by BorisBarzotto** [comment]
Hi, I need to migrate from 0.3 to 0.5, is there anything I need to be aware of? can I migrate without any news? I am only using the indications in the supabase tutorials to use this dependency, I don't know if there is anything new I should modify.

**Comment by J0** [comment]
Hey all,

Thanks for flagging the issue. The Custom Access Token Hook should work on the latest version of SSR. If you are facing issues do feel free to write back or open a ticket via supabase.help referencing this issue.

Thanks
