### ISSUE TITLE
Update official guide since cookies() becomes async with Next.js 15

### ISSUE THREAD

**Issue by whollacsek** [supabase/ssr#75]
I think the official guide https://supabase.com/docs/guides/auth/server-side/nextjs needs to be updated to take into account  https://nextjs.org/docs/canary/app/building-your-application/upgrading/version-15#async-request-apis-breaking-change. This means `createClient()` will be async from now on, the impact should be minimal in user's code but I'm wondering if the official recommendation of "just create new instances as needed" still holds

**Comment by valentin-marquez** [comment]
I also wanted to update and some problems popped up, I was able to fix them by following the new nextjs cookie guide.
I also modified my server.ts to work asynchronously like this:

```ts
import { createServerClient, type CookieOptions } from "@supabase/ssr";
import { cookies } from "next/headers";
import { Database } from "../types/supabase";

let cachedClient: ReturnType<typeof createServerClient<Database>> | null = null;

export async function createClient() {
  if (cachedClient) return cachedClient;

  const cookieStore = await cookies();

  cachedClient = createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value, ...options });
          } catch (error) {
            // The `set` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
        remove(name: string, options: CookieOptions) {
          try {
            cookieStore.set({ name, value: "", ...options });
          } catch (error) {
            // The `delete` method was called from a Server Component.
            // This can be ignored if you have middleware refreshing
            // user sessions.
          }
        },
      },
    }
  );

  return cachedClient;
}

````

although I would really prefer the official solution.

**Comment by siimsams** [comment]
I guess we need to await the cookies inside the library aswell for next.js. I might take a look at it once I upgrade my project.

**Comment by charislam** [comment]
Thanks for raising the issue! The guide should be updated now to accommodate the new async methods.
